/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CustomerWelcomeRouteImport } from './routes/customer.welcome'
import { Route as CustomerReviewRouteImport } from './routes/customer.review'
import { Route as CustomerPhotosRouteImport } from './routes/customer.photos'
import { Route as CustomerPhotoSelectionRouteImport } from './routes/customer.photo-selection'
import { Route as CustomerFramesRouteImport } from './routes/customer.frames'
import { Route as CustomerFrameSelectionRouteImport } from './routes/customer.frame-selection'
import { Route as CustomerFrameRouteImport } from './routes/customer.frame'
import { Route as CustomerFinishRouteImport } from './routes/customer.finish'
import { Route as CustomerEditorRouteImport } from './routes/customer.editor'
import { Route as CustomerDoneRouteImport } from './routes/customer.done'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AdminSessionRouteImport } from './routes/admin.session'
import { Route as AdminOutputRouteImport } from './routes/admin.output'
import { Route as AdminGeneralRouteImport } from './routes/admin.general'
import { Route as AdminFramesRouteImport } from './routes/admin.frames'
import { Route as AdminBrandRouteImport } from './routes/admin.brand'
import { Route as ApiV1UploadRouteImport } from './routes/api/v1/upload'
import { Route as ApiV1SettingsRouteImport } from './routes/api/v1/settings'
import { Route as ApiV1SessionsRouteImport } from './routes/api/v1/sessions'
import { Route as ApiV1FramesRouteImport } from './routes/api/v1/frames'
import { Route as ApiV1BrandsRouteImport } from './routes/api/v1/brands'
import { Route as ApiV1AuthRouteImport } from './routes/api/v1/auth'

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerWelcomeRoute = CustomerWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerReviewRoute = CustomerReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPhotosRoute = CustomerPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPhotoSelectionRoute = CustomerPhotoSelectionRouteImport.update({
  id: '/photo-selection',
  path: '/photo-selection',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerFramesRoute = CustomerFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerFrameSelectionRoute = CustomerFrameSelectionRouteImport.update({
  id: '/frame-selection',
  path: '/frame-selection',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerFrameRoute = CustomerFrameRouteImport.update({
  id: '/frame',
  path: '/frame',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerFinishRoute = CustomerFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerEditorRoute = CustomerEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDoneRoute = CustomerDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => CustomerRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionRoute = AdminSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOutputRoute = AdminOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralRoute = AdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFramesRoute = AdminFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandRoute = AdminBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AdminRoute,
} as any)
const ApiV1UploadRoute = ApiV1UploadRouteImport.update({
  id: '/api/v1/upload',
  path: '/api/v1/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsRoute = ApiV1SettingsRouteImport.update({
  id: '/api/v1/settings',
  path: '/api/v1/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionsRoute = ApiV1SessionsRouteImport.update({
  id: '/api/v1/sessions',
  path: '/api/v1/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FramesRoute = ApiV1FramesRouteImport.update({
  id: '/api/v1/frames',
  path: '/api/v1/frames',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BrandsRoute = ApiV1BrandsRouteImport.update({
  id: '/api/v1/brands',
  path: '/api/v1/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthRoute = ApiV1AuthRouteImport.update({
  id: '/api/v1/auth',
  path: '/api/v1/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/admin/brand': typeof AdminBrandRoute
  '/admin/frames': typeof AdminFramesRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/output': typeof AdminOutputRoute
  '/admin/session': typeof AdminSessionRoute
  '/api/mcp': typeof ApiMcpRoute
  '/customer/done': typeof CustomerDoneRoute
  '/customer/editor': typeof CustomerEditorRoute
  '/customer/finish': typeof CustomerFinishRoute
  '/customer/frame': typeof CustomerFrameRoute
  '/customer/frame-selection': typeof CustomerFrameSelectionRoute
  '/customer/frames': typeof CustomerFramesRoute
  '/customer/photo-selection': typeof CustomerPhotoSelectionRoute
  '/customer/photos': typeof CustomerPhotosRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/welcome': typeof CustomerWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/api/v1/auth': typeof ApiV1AuthRoute
  '/api/v1/brands': typeof ApiV1BrandsRoute
  '/api/v1/frames': typeof ApiV1FramesRoute
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/v1/settings': typeof ApiV1SettingsRoute
  '/api/v1/upload': typeof ApiV1UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/brand': typeof AdminBrandRoute
  '/admin/frames': typeof AdminFramesRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/output': typeof AdminOutputRoute
  '/admin/session': typeof AdminSessionRoute
  '/api/mcp': typeof ApiMcpRoute
  '/customer/done': typeof CustomerDoneRoute
  '/customer/editor': typeof CustomerEditorRoute
  '/customer/finish': typeof CustomerFinishRoute
  '/customer/frame': typeof CustomerFrameRoute
  '/customer/frame-selection': typeof CustomerFrameSelectionRoute
  '/customer/frames': typeof CustomerFramesRoute
  '/customer/photo-selection': typeof CustomerPhotoSelectionRoute
  '/customer/photos': typeof CustomerPhotosRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/welcome': typeof CustomerWelcomeRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/api/v1/auth': typeof ApiV1AuthRoute
  '/api/v1/brands': typeof ApiV1BrandsRoute
  '/api/v1/frames': typeof ApiV1FramesRoute
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/v1/settings': typeof ApiV1SettingsRoute
  '/api/v1/upload': typeof ApiV1UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/admin/brand': typeof AdminBrandRoute
  '/admin/frames': typeof AdminFramesRoute
  '/admin/general': typeof AdminGeneralRoute
  '/admin/output': typeof AdminOutputRoute
  '/admin/session': typeof AdminSessionRoute
  '/api/mcp': typeof ApiMcpRoute
  '/customer/done': typeof CustomerDoneRoute
  '/customer/editor': typeof CustomerEditorRoute
  '/customer/finish': typeof CustomerFinishRoute
  '/customer/frame': typeof CustomerFrameRoute
  '/customer/frame-selection': typeof CustomerFrameSelectionRoute
  '/customer/frames': typeof CustomerFramesRoute
  '/customer/photo-selection': typeof CustomerPhotoSelectionRoute
  '/customer/photos': typeof CustomerPhotosRoute
  '/customer/review': typeof CustomerReviewRoute
  '/customer/welcome': typeof CustomerWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/api/v1/auth': typeof ApiV1AuthRoute
  '/api/v1/brands': typeof ApiV1BrandsRoute
  '/api/v1/frames': typeof ApiV1FramesRoute
  '/api/v1/sessions': typeof ApiV1SessionsRoute
  '/api/v1/settings': typeof ApiV1SettingsRoute
  '/api/v1/upload': typeof ApiV1UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/admin/brand'
    | '/admin/frames'
    | '/admin/general'
    | '/admin/output'
    | '/admin/session'
    | '/api/mcp'
    | '/customer/done'
    | '/customer/editor'
    | '/customer/finish'
    | '/customer/frame'
    | '/customer/frame-selection'
    | '/customer/frames'
    | '/customer/photo-selection'
    | '/customer/photos'
    | '/customer/review'
    | '/customer/welcome'
    | '/admin/'
    | '/customer/'
    | '/api/v1/auth'
    | '/api/v1/brands'
    | '/api/v1/frames'
    | '/api/v1/sessions'
    | '/api/v1/settings'
    | '/api/v1/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/brand'
    | '/admin/frames'
    | '/admin/general'
    | '/admin/output'
    | '/admin/session'
    | '/api/mcp'
    | '/customer/done'
    | '/customer/editor'
    | '/customer/finish'
    | '/customer/frame'
    | '/customer/frame-selection'
    | '/customer/frames'
    | '/customer/photo-selection'
    | '/customer/photos'
    | '/customer/review'
    | '/customer/welcome'
    | '/admin'
    | '/customer'
    | '/api/v1/auth'
    | '/api/v1/brands'
    | '/api/v1/frames'
    | '/api/v1/sessions'
    | '/api/v1/settings'
    | '/api/v1/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/admin/brand'
    | '/admin/frames'
    | '/admin/general'
    | '/admin/output'
    | '/admin/session'
    | '/api/mcp'
    | '/customer/done'
    | '/customer/editor'
    | '/customer/finish'
    | '/customer/frame'
    | '/customer/frame-selection'
    | '/customer/frames'
    | '/customer/photo-selection'
    | '/customer/photos'
    | '/customer/review'
    | '/customer/welcome'
    | '/admin/'
    | '/customer/'
    | '/api/v1/auth'
    | '/api/v1/brands'
    | '/api/v1/frames'
    | '/api/v1/sessions'
    | '/api/v1/settings'
    | '/api/v1/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
  ApiV1AuthRoute: typeof ApiV1AuthRoute
  ApiV1BrandsRoute: typeof ApiV1BrandsRoute
  ApiV1FramesRoute: typeof ApiV1FramesRoute
  ApiV1SessionsRoute: typeof ApiV1SessionsRoute
  ApiV1SettingsRoute: typeof ApiV1SettingsRoute
  ApiV1UploadRoute: typeof ApiV1UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/welcome': {
      id: '/customer/welcome'
      path: '/welcome'
      fullPath: '/customer/welcome'
      preLoaderRoute: typeof CustomerWelcomeRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/review': {
      id: '/customer/review'
      path: '/review'
      fullPath: '/customer/review'
      preLoaderRoute: typeof CustomerReviewRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/photos': {
      id: '/customer/photos'
      path: '/photos'
      fullPath: '/customer/photos'
      preLoaderRoute: typeof CustomerPhotosRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/photo-selection': {
      id: '/customer/photo-selection'
      path: '/photo-selection'
      fullPath: '/customer/photo-selection'
      preLoaderRoute: typeof CustomerPhotoSelectionRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/frames': {
      id: '/customer/frames'
      path: '/frames'
      fullPath: '/customer/frames'
      preLoaderRoute: typeof CustomerFramesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/frame-selection': {
      id: '/customer/frame-selection'
      path: '/frame-selection'
      fullPath: '/customer/frame-selection'
      preLoaderRoute: typeof CustomerFrameSelectionRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/frame': {
      id: '/customer/frame'
      path: '/frame'
      fullPath: '/customer/frame'
      preLoaderRoute: typeof CustomerFrameRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/finish': {
      id: '/customer/finish'
      path: '/finish'
      fullPath: '/customer/finish'
      preLoaderRoute: typeof CustomerFinishRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/editor': {
      id: '/customer/editor'
      path: '/editor'
      fullPath: '/customer/editor'
      preLoaderRoute: typeof CustomerEditorRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/done': {
      id: '/customer/done'
      path: '/done'
      fullPath: '/customer/done'
      preLoaderRoute: typeof CustomerDoneRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/session': {
      id: '/admin/session'
      path: '/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AdminSessionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/output': {
      id: '/admin/output'
      path: '/output'
      fullPath: '/admin/output'
      preLoaderRoute: typeof AdminOutputRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/general': {
      id: '/admin/general'
      path: '/general'
      fullPath: '/admin/general'
      preLoaderRoute: typeof AdminGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/frames': {
      id: '/admin/frames'
      path: '/frames'
      fullPath: '/admin/frames'
      preLoaderRoute: typeof AdminFramesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brand': {
      id: '/admin/brand'
      path: '/brand'
      fullPath: '/admin/brand'
      preLoaderRoute: typeof AdminBrandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/v1/upload': {
      id: '/api/v1/upload'
      path: '/api/v1/upload'
      fullPath: '/api/v1/upload'
      preLoaderRoute: typeof ApiV1UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings': {
      id: '/api/v1/settings'
      path: '/api/v1/settings'
      fullPath: '/api/v1/settings'
      preLoaderRoute: typeof ApiV1SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sessions': {
      id: '/api/v1/sessions'
      path: '/api/v1/sessions'
      fullPath: '/api/v1/sessions'
      preLoaderRoute: typeof ApiV1SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/frames': {
      id: '/api/v1/frames'
      path: '/api/v1/frames'
      fullPath: '/api/v1/frames'
      preLoaderRoute: typeof ApiV1FramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/brands': {
      id: '/api/v1/brands'
      path: '/api/v1/brands'
      fullPath: '/api/v1/brands'
      preLoaderRoute: typeof ApiV1BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth': {
      id: '/api/v1/auth'
      path: '/api/v1/auth'
      fullPath: '/api/v1/auth'
      preLoaderRoute: typeof ApiV1AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBrandRoute: typeof AdminBrandRoute
  AdminFramesRoute: typeof AdminFramesRoute
  AdminGeneralRoute: typeof AdminGeneralRoute
  AdminOutputRoute: typeof AdminOutputRoute
  AdminSessionRoute: typeof AdminSessionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandRoute: AdminBrandRoute,
  AdminFramesRoute: AdminFramesRoute,
  AdminGeneralRoute: AdminGeneralRoute,
  AdminOutputRoute: AdminOutputRoute,
  AdminSessionRoute: AdminSessionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerDoneRoute: typeof CustomerDoneRoute
  CustomerEditorRoute: typeof CustomerEditorRoute
  CustomerFinishRoute: typeof CustomerFinishRoute
  CustomerFrameRoute: typeof CustomerFrameRoute
  CustomerFrameSelectionRoute: typeof CustomerFrameSelectionRoute
  CustomerFramesRoute: typeof CustomerFramesRoute
  CustomerPhotoSelectionRoute: typeof CustomerPhotoSelectionRoute
  CustomerPhotosRoute: typeof CustomerPhotosRoute
  CustomerReviewRoute: typeof CustomerReviewRoute
  CustomerWelcomeRoute: typeof CustomerWelcomeRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerDoneRoute: CustomerDoneRoute,
  CustomerEditorRoute: CustomerEditorRoute,
  CustomerFinishRoute: CustomerFinishRoute,
  CustomerFrameRoute: CustomerFrameRoute,
  CustomerFrameSelectionRoute: CustomerFrameSelectionRoute,
  CustomerFramesRoute: CustomerFramesRoute,
  CustomerPhotoSelectionRoute: CustomerPhotoSelectionRoute,
  CustomerPhotosRoute: CustomerPhotosRoute,
  CustomerReviewRoute: CustomerReviewRoute,
  CustomerWelcomeRoute: CustomerWelcomeRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
  ApiV1AuthRoute: ApiV1AuthRoute,
  ApiV1BrandsRoute: ApiV1BrandsRoute,
  ApiV1FramesRoute: ApiV1FramesRoute,
  ApiV1SessionsRoute: ApiV1SessionsRoute,
  ApiV1SettingsRoute: ApiV1SettingsRoute,
  ApiV1UploadRoute: ApiV1UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
